# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
