# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='rank',
            new_name='rating',
        ),
    ]
