# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='idea_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_ref', to='idea.Idea'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
